### ISSUE TITLE
One of the lists in the footer wraps underneath the copyright

### ISSUE THREAD

**Issue by OldDragon2A** [lagtv/lagtv#208]
Simple enough to fix, just need to add this:

``` css
footer ul:last-of-type(1) { margin-left: 1.5em; }
```

I'm just not sure if I should make a branch just to fix that.
